databases:
  - name: pictute_app_nella
    databaseName: pictute_app_nella
    user: pictute_app_nella_user
services:
  - type: web
    name: pictute_app_nella
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pictute_app_nella
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false