development:
  cloud_name: dgbq5v6dk
  api_key: 191631119444689
  api_secret: yqINNuZ49sHBIevlolhA-zia_l0
  secure: true
  enhance_image_tag: true
  static_file_support: false

test:
  cloud_name: dgbq5v6dk
  api_key: 191631119444689
  api_secret: yqINNuZ49sHBIevlolhA-zia_l0
  secure: true
  enhance_image_tag: true
  static_file_support: false

production:
  cloud_name: dgbq5v6dk
  api_key: 191631119444689
  api_secret: yqINNuZ49sHBIevlolhA-zia_l0
  secure: true
  enhance_image_tag: true
  static_file_support: true
